### PR TITLE
Style the page

### PR DESCRIPTION
**Pull request by erizocosmico**

### CODE REVIEW

**Comment by vmarkovtsev** [comment]
I guess we need `git add scripts/scripts.js`

**Comment by erizocosmico** [comment]
It's there https://github.com/mvader/tab-vs-spaces/blob/cosmetics/js/scripts.js

**Comment by erizocosmico** [comment]
@vmarkovtsev ready to be merged

**Comment by vmarkovtsev** [comment]
Thanks!

**Pull request merged**
